### ISSUE TITLE
I can't install this thing

### ISSUE THREAD

**Issue by yeahthisiscuddy** [roigrp/ROI.plugin.gurobi#1]
None of the installation paths works for me. I either get "doesn't exist in R 3.6" or "gurobi.dll couldn't be found" errors.

**Comment by FlorianSchwendinger** [comment]
This means you have install issues with the `gurobi` package. `ROI.plugin.gurobi` uses the `gurobi` package and therefore never directly interacts with the `.dll`. For information on how to install the `gurobi` package see the [Gurobi-homepage](https://www.gurobi.com/documentation/8.1/quickstart_mac/r_installing_the_r_package.html).
