### ISSUE TITLE
Not compatible with R 3.6.1?

### ISSUE THREAD

**Issue by prof-anderson** [roigrp/ROI.plugin.gurobi#2]
Just installed gurobi 8.1.1 on a Windows 10 computer.  Tried to install the roi.plugin.gurobi and received a message 

Warning in install.packages :
  package ‘ROI.plugin.gurobi’ is not available (for R version 3.6.1)

I followed the directions in the readme.MD  
`install.packages("ROI.plugin.gurobi", repos="http://R-Forge.R-project.org")`

Is there another route to do it?  I've been using various solvers (glpk, lpsolve, symphony) and was looking forward to trying gurobi on bigger problems.

Thanks,
Tim

**Comment by FlorianSchwendinger** [comment]
The build on R-Forge fails since gurobi and the gurobi R-package are not installed on R-Forge. 
Please use 
```
## or (recommended version)
remotes:::install_svn("svn://svn.r-forge.r-project.org/svnroot/roi/pkg/ROI.plugin.gurobi")
## or
remotes:::install_github("FlorianSchwendinger/ROI.plugin.gurobi")
```
instead.
