### ISSUE TITLE
Can't install ROI.plugin.gurobi

### ISSUE THREAD

**Issue by snestler** [roigrp/ROI.plugin.gurobi#3]
> remotes:::install_github("FlorianSchwendinger/ROI.plugin.gurobi")
Downloading GitHub repo FlorianSchwendinger/ROI.plugin.gurobi@master
Skipping 1 packages not available: gurobi
✔  checking for file ‘/tmp/Rtmp31S71e/remotes8011278d2c83/FlorianSchwendinger-ROI.plugin.gurobi-a76d88e/DESCRIPTION’ ...
─  preparing ‘ROI.plugin.gurobi’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ROI.plugin.gurobi_0.3-0.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘ROI.plugin.gurobi’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: package ‘gurobi’ was installed before R 4.0.0: please re-install it
Execution halted
ERROR: lazy loading failed for package ‘ROI.plugin.gurobi’
* removing ‘/usr/local/lib/R/site-library/ROI.plugin.gurobi’
Error: Failed to install 'ROI.plugin.gurobi' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp31S71e/file801128eb486a/ROI.plugin.gurobi_0.3-0.tar.gz’ had non-zero exit status

**Comment by FlorianSchwendinger** [comment]
Did the gurobi installation work? 
You have to install the gurobi package first (since it is listed as import in the DESCRIPTION file).
https://www.gurobi.com/documentation/9.0/refman/ins_the_r_package.html
As far as I saw there is currently no gurobi package built for R 4.
