### ISSUE TITLE
Issue installing on 64 bit R

### ISSUE THREAD

**Issue by mmcgarity** [roigrp/ROI.plugin.gurobi#5]
I'm having trouble installing the plugin on 64 bit R on a Windows 10 64 bit machine running R 4.0.3:

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

library(remotes)
Warning message:
package 'remotes' was built under R version 4.0.5
install_github("FlorianSchwendinger/ROI.plugin.gurobi")
Downloading GitHub repo FlorianSchwendinger/ROI.plugin.gurobi@HEAD
Skipping 1 packages not available: gurobi
v checking for file 'C:\Users\Mike\AppData\Local\Temp\Rtmp48g9a4\remotes2630457fb54\roigrp-ROI.plugin.gurobi-ca34a4d/DESCRIPTION'

preparing 'ROI.plugin.gurobi':
v checking DESCRIPTION meta-information ...
checking for LF line-endings in source and make files and shell scripts
checking for empty or unneeded directories
building 'ROI.plugin.gurobi_0.4-0.tar.gz'
Installing package into 'C:/Users/Mike/OneDrive - Johns Hopkins/Documents/R/win-library/4.0'
(as 'lib' is unspecified)

installing source package 'ROI.plugin.gurobi' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
converting help for package 'ROI.plugin.gurobi'
finding HTML links ... done
Example_01 html
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'ROI.plugin.gurobi' in library.dynam(lib, package, package.lib):
DLL 'gurobi' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
removing 'C:/Users/Mike/OneDrive - Johns Hopkins/Documents/R/win-library/4.0/ROI.plugin.gurobi'
Warning message:
In i.p(...) :
installation of package 'C:/Users/Mike/AppData/Local/Temp/Rtmp48g9a4/file2630203b1c6e/ROI.plugin.gurobi_0.4-0.tar.gz' had non-zero exit status
library(gurobi)
Loading required package: slam
install_github("FlorianSchwendinger/ROI.plugin.gurobi")
Downloading GitHub repo FlorianSchwendinger/ROI.plugin.gurobi@HEAD
Skipping 1 packages not available: gurobi
v checking for file 'C:\Users\Mike\AppData\Local\Temp\Rtmp48g9a4\remotes2630139bf78\roigrp-ROI.plugin.gurobi-ca34a4d/DESCRIPTION'

preparing 'ROI.plugin.gurobi':
v checking DESCRIPTION meta-information ...
checking for LF line-endings in source and make files and shell scripts
checking for empty or unneeded directories
building 'ROI.plugin.gurobi_0.4-0.tar.gz'
Installing package into 'C:/Users/Mike/OneDrive - Johns Hopkins/Documents/R/win-library/4.0'
(as 'lib' is unspecified)

installing source package 'ROI.plugin.gurobi' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
converting help for package 'ROI.plugin.gurobi'
finding HTML links ... done
Example_01 html
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'ROI.plugin.gurobi' in library.dynam(lib, package, package.lib):
DLL 'gurobi' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
removing 'C:/Users/Mike/OneDrive - Johns Hopkins/Documents/R/win-library/4.0/ROI.plugin.gurobi'
Warning message:
In i.p(...) :
installation of package 'C:/Users/Mike/AppData/Local/Temp/Rtmp48g9a4/file26303d534d1a/ROI.plugin.gurobi_0.4-0.tar.gz' had non-zero exit status

**Comment by nouran-mohamed-1** [comment]
I have been facing the same problem for two weeks till now and I can't find a solution for this.

**Comment by FlorianSchwendinger** [comment]
The error message seams to tell you that you don't have gurobi installed for `arch - i386`.
So you could try
```r
install_github("FlorianSchwendinger/ROI.plugin.gurobi", INSTALL_opts="--no-multiarch")
```
 if your default architecture ist `x64` and the gurobi package is correctly is installed in x64 this should work.

**Comment by mmcgarity** [comment]
That worked for me. Thanks very much!
