### ISSUE TITLE
"had non-zero exit status"

### ISSUE THREAD

**Issue by Hujinii** [roigrp/ROI.plugin.gurobi#6]
Hi,
I just installed "roigrp/ROI.plugin.gurobi", but it still reports errors of "had non-zero exit status". Could you please let me know theres a potential solution? thanks a lot. The "gurobi" library was installed successful, since I can load it in the library.  

R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

> library(slam)
> library(gurobi)
> remotes:::install_github("roigrp/ROI.plugin.gurobi")
Downloading GitHub repo roigrp/ROI.plugin.gurobi@HEAD
Skipping 1 packages not available: gurobi
√  checking for file 'C:\Users\3873277\AppData\Local\Temp\Rtmp8C5AbM\remotesad6816012d4d\roigrp-ROI.plugin.gurobi-ca34a4d/DESCRIPTION' (582ms)
-  preparing 'ROI.plugin.gurobi':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ROI.plugin.gurobi_0.4-0.tar.gz'
   
Installing package into ‘C:/Users/3873277/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/3873277/AppData/Local/Temp/Rtmp8C5AbM/filead6859a11b0c/ROI.plugin.gurobi_0.4-0.tar.gz’ had non-zero exit status**

**Comment by FlorianSchwendinger** [comment]
I tried it now on Debian and on Windows and at both it works.
On Windows I need to add `INSTALL_opts="--no-multiarch"` since I have only the 64 bit version installed.
```{r}
remotes::install_github("roigrp/ROI.plugin.gurobi", INSTALL_opts="--no-multiarch")
```
I would guess you face the same issue. But I see the following output on Windows if I try without multiarch
```
> remotes::install_github("roigrp/ROI.plugin.gurobi")
Downloading GitHub repo roigrp/ROI.plugin.gurobi@HEAD
Skipping 1 packages not available: gurobi
Running `R CMD build`...
* checking for file 'C:\Users\schwe\AppData\Local\Temp\RtmpmQyVhR\remotes3f04a72183\roigrp-ROI.plugin.gurobi-ca34a4d/DESCRIPTION' ... OK
* preparing 'ROI.plugin.gurobi':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'ROI.plugin.gurobi_0.4-0.tar.gz'
* installing *source* package 'ROI.plugin.gurobi' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'ROI.plugin.gurobi'
    finding HTML links ... done
    Example_01                              html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'ROI.plugin.gurobi' in library.dynam(lib, package, package.lib):
 DLL 'gurobi' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Software/R-4.1.1/library/ROI.plugin.gurobi'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/schwe/AppData/Local/Temp/RtmpmQyVhR/file3f0407d3c5f/ROI.plugin.gurobi_0.4-0.tar.gz’ had non-zero exit status
```
from this it is easy to see that the `arch - i386` package is missing and therefore the `INSTALL_opts="--no-multiarch"` has to be set.

If this should not work for you please post the outputs of the following
- 1.
```{r}
library(remotes)
library(slam)
library(ROI)
library(gurobi)
sessionInfo()
```
- 2. The ouptput of running the following example `https://www.gurobi.com/documentation/9.1/quickstart_windows/r_example.html` .

**Comment by Hujinii** [comment]
Hi, thanks so much for the fast reply. I have tried the code, but unfortunately I didnt work (non-zero exit status)

> remotes::install_github("roigrp/ROI.plugin.gurobi", INSTALL_opts="--no-multiarch")
Downloading GitHub repo roigrp/ROI.plugin.gurobi@HEAD
Skipping 1 packages not available: gurobi
√  checking for file 'C:\Users\3873277\AppData\Local\Temp\Rtmp8C5AbM\remotesad6837e5146\roigrp-ROI.plugin.gurobi-ca34a4d/DESCRIPTION' (779ms)
-  preparing 'ROI.plugin.gurobi':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ROI.plugin.gurobi_0.4-0.tar.gz'
   
Installing package into ‘C:/Users/3873277/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/3873277/AppData/Local/Temp/Rtmp8C5AbM/filead685b0d722f/ROI.plugin.gurobi_0.4-0.tar.gz’ had non-zero exit status

I had the outoputs
1)
> library(remotes)
> 
> library(slam)
> 
> library(gurobi)
> 
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] remotes_2.4.1      Matrix_1.3-4       gurobi_9.1-2       slam_0.1-48        rgdal_1.5-27       raster_3.4-13     
 [7] tibble_3.1.4       scales_1.1.1       gridExtra_2.3      ggplot2_3.3.5      lubridate_1.7.10   dplyr_1.0.7       
[13] RColorBrewer_1.1-2 chron_2.3-56       lattice_0.20-44    reshape2_1.4.4     maps_3.4.0         maptools_1.1-2    
[19] sp_1.4-5           fields_12.5        viridis_0.6.1      viridisLite_0.4.0  spam_2.7-0         dotCall64_1.0-1   

loaded via a namespace (and not attached):
 [1] zoo_1.8-9                  tidyselect_1.1.1           purrr_0.3.4                colorspace_2.0-2          
 [5] vctrs_0.3.8                generics_0.1.0             pkgbuild_1.2.0             utf8_1.2.2                
 [9] rlang_0.4.11               pillar_1.6.3               foreign_0.8-81             glue_1.4.2                
[13] withr_2.4.2                PortfolioAnalytics_1.1.0   foreach_1.5.1              lifecycle_1.0.1           
[17] plyr_1.8.6                 stringr_1.4.0              munsell_0.5.0              gtable_0.3.0              
[21] codetools_0.2-18           callr_3.7.0                ps_1.6.0                   parallel_4.1.1            
[25] curl_4.3.2                 fansi_0.5.0                PerformanceAnalytics_2.0.4 xts_0.12.1                
[29] Rcpp_1.0.7                 stringi_1.7.4              processx_3.5.2             rprojroot_2.0.2           
[33] cli_3.0.1                  quadprog_1.5-8             tools_4.1.1                magrittr_2.0.1            
[37] crayon_1.4.1               pkgconfig_2.0.3            ellipsis_0.3.2             prettyunits_1.1.1         
[41] rstudioapi_0.13            iterators_1.0.13           R6_2.5.1                   compiler_4.1.1            
> 

ii) > library(gurobi)
> 
> model <- list()
> 
> model$A          <- matrix(c(1,2,3,1,1,0), nrow=2, ncol=3, byrow=T)
> model$obj        <- c(1,1,2)
> model$modelsense <- 'max'
> model$rhs        <- c(4,1)
> model$sense      <- c('<', '>')
> model$vtype      <- 'B'
> 
> params <- list(OutputFlag=0)
> 
> result <- gurobi(model, params)
> 
> print('Solution:')
[1] "Solution:"
> print(result$objval)
[1] 3
> print(result$x)
[1] 1 0 1
>

**Comment by FlorianSchwendinger** [comment]
OK. This seams fine. Which **ROI** version do you have installed?
```{r}
library(ROI)
sessionInfo()
```

What ide are you using? Since your output 
```{r}
remotes::install_github("roigrp/ROI.plugin.gurobi", INSTALL_opts="--no-multiarch")
Downloading GitHub repo roigrp/ROI.plugin.gurobi@HEAD
Skipping 1 packages not available: gurobi
√ checking for file 'C:\Users\3873277\AppData\Local\Temp\Rtmp8C5AbM\remotesad6837e5146\roigrp-ROI.plugin.gurobi-ca34a4d/DESCRIPTION' (779ms)

preparing 'ROI.plugin.gurobi':
√ checking DESCRIPTION meta-information ...
checking for LF line-endings in source and make files and shell scripts
checking for empty or unneeded directories
building 'ROI.plugin.gurobi_0.4-0.tar.gz'
Installing package into ‘C:/Users/3873277/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning message:
In i.p(...) :
installation of package ‘C:/Users/3873277/AppData/Local/Temp/Rtmp8C5AbM/filead685b0d722f/ROI.plugin.gurobi_0.4-0.tar.gz’ had non-zero exit status
```
seams to hide information. It is not an output as generated by **R** but already transformed by something.

In general I find it unlikely that there is an installation issue in **ROI,plugin.gurobi** since it has not much dependencies and contains no compiled code.

**Comment by Hujinii** [comment]
Hi, its ROI 1.0_0. I use the latest version of RStudio. Do you thinkk I should try to instlal them in R?


> library(ROI)
> 
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ROI_1.0-0

loaded via a namespace (and not attached):
 [1] quadprog_1.5-8            prettyunits_1.1.1         ps_1.6.0                  withr_2.4.2              
 [5] rprojroot_2.0.2           crayon_1.4.1              ROI.plugin.alabama_1.0-0  slam_0.1-48              
 [9] R6_2.5.1                  registry_0.5-1            ROI.plugin.glpk_1.0-0     alabama_2015.3-1         
[13] cli_3.0.1                 curl_4.3.2                rstudioapi_0.13           remotes_2.4.1            
[17] callr_3.7.0               Rsymphony_0.1-31          ROI.plugin.quadprog_1.0-0 tools_4.1.1              
[21] processx_3.5.2            numDeriv_2016.8-1.1       compiler_4.1.1            pkgbuild_1.2.0           
[25] ROI.plugin.symphony_1.0-0 Rglpk_0.6-4

**Comment by FlorianSchwendinger** [comment]
Maybe try
```{r}
pkgs <- "https://github.com/roigrp/ROI.plugin.gurobi/releases/download/gurobi9/ROI.plugin.gurobi_0.4-0.zip"
install.packages(pkgs)
```

**Comment by Hujinii** [comment]
Hi it shows A version of this package for your version of R might be available elsewhere, Shall I reinstall R to an earlier version? Thanks


> pkgs <- "https://github.com/roigrp/ROI.plugin.gurobi/releases/download/gurobi9/ROI.plugin.gurobi_0.4-0.zip"
> install.packages(pkgs)
Installing package into ‘C:/Users/3873277/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘https://github.com/roigrp/ROI.plugin.gurobi/releases/download/gurobi9/ROI.plugin.gurobi_0.4-0.zip’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by FlorianSchwendinger** [comment]
I don't think the version is the issue. Since I build the .zip file with
```
R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
```

But I have no Idea why it doesn't work.
You could try to download 
https://github.com/roigrp/ROI.plugin.gurobi/releases/download/gurobi9/ROI.plugin.gurobi_0.4-0.tar.gz

and install with base R from the local package
```{r}
install.packages("ROI.plugin.gurobi_0.4-0.tar.gz",
                 repos = NULL, type = "source",
                 INSTALL_opts = "--no-multiarch")
```

**Comment by Hujinii** [comment]
Thanks so much man! I use Rstudio to install the zip file locally and now it works. The ROI plugin solver gurobi is installed successfully and the library can be loaded. Its great now I can use a much better solver.   
It warns me to install Rtools, but seems that it can be installed without Rtools.


> install.packages("C:/Program Files/R/R-4.1.1/library/ROI.plugin.gurobi_0.4-0.tar.gz",
+                  repos = NULL, type = "source",
+                  INSTALL_opts = "--no-multiarch")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/3873277/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'ROI.plugin.gurobi' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'ROI.plugin.gurobi'
    finding HTML links ... done
    Example_01                              html  
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ROI.plugin.gurobi)
*
> library(ROI.plugin.gurobi)
